### ISSUE TITLE
Click extension or print button after installing does nothing

### ISSUE THREAD

**Issue by TristanBossa** [m-radzikowski/youtrack-issue-cards-printer#5]
As mentioned in the title after installing the extension printing broke.

The console shows this error:

Uncaught TypeError: Cannot read property 'replaceAll' of undefined
    at Webr.component.ComponentRegistry._normalize (bundledJavaScript-1277617f402c6d62276d3c1c1e111a1a.js:32)
    at Webr.component.ComponentRegistry.getComponentSource (bundledJavaScript-1277617f402c6d62276d3c1c1e111a1a.js:28)
    at Webr.component.ComponentRegistry.createServerEventConfig (bundledJavaScript-1277617f402c6d62276d3c1c1e111a1a.js:27)
    at HTMLButtonElement.Webr.component.ComponentRegistry.serverHandler (bundledJavaScript-1277617f402c6d62276d3c1c1e111a1a.js:30)
    at HTMLButtonElement.dispatch (bundledJavaScript-1277617f402c6d62276d3c1c1e111a1a.js:144)
    at HTMLButtonElement.v.handle (bundledJavaScript-1277617f402c6d62276d3c1c1e111a1a.js:144)

**Comment by m-radzikowski** [comment]
Hey,
could you please provide your YouTrack version and Chrome version?

**Comment by TristanBossa** [comment]
Youtrack version is: 2017.4
Chrome is: Version 63.0.3239.132 (Official Build) (64-bit)

**Comment by m-radzikowski** [comment]
The error you pasted is not from the extension, but from YouTrack itself. `bundledJavaScript-HASH.js` is YT script. And extension does not call any of YT methods, so the error is weird and probably unrelated to extension?

I've tested the extension on the same version of Chrome and the same version of YT, and it works well on my few machines. To find further info please:
- go to chrome://extensions/
- enable developer mode
- find extension on the list
- click "background page", popup with console should open
- go to YouTrack, refresh page and click on the extension to print issues - does console show any logs?

**Comment by TristanBossa** [comment]
Sorry for the delay here is the info you asked for:

When showing the background page console i get this error:

`VM48:1 Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at XMLHttpRequest.xhr.onreadystatechange (page-action.js:44)
xhr.onreadystatechange @ page-action.js:44
XMLHttpRequest.send (async)
fetchIssues @ page-action.js:62
(anonymous) @ page-action.js:84
safeCallbackApply @ extensions::uncaught_exception_handler:27
handleResponse @ extensions::sendRequest:67`

The print button definitely works without the extension installed and stops working when its installed

**Comment by m-radzikowski** [comment]
Ok, it looks like a problem with YouTrack REST API call. Please:

1. Go to JetBrains YouTrack: https://youtrack.jetbrains.com/issues, click print button (or extension icon), does the print page (from the extension) open? You don't have to be logged in.

2. Check your YouTrack instance REST API - go here: https://client.restlet.com/#share=https://client.restlet.com/api/share/5a5d0d44a0b6db0ab077684d, change address from `youtrack.jetbrains.com` to your instance URL, and send a request. You should get JSON (not XML!) in response, with Content-Type header "application/json:charset=utf8". Could you verify it for me?

**Comment by TristanBossa** [comment]
Okay using the extension on the youtrack issue url works fine for me.

When checking our REST API I get the result in the attached image
![youtrackrestresult](https://user-images.githubusercontent.com/35366303/34982565-aa01326e-faa2-11e7-91d0-3e5d0bd42f17.png)

**Comment by m-radzikowski** [comment]
Hi,
I've just published fixed version 0.1.1. It should generate issues from your YouTrack instance properly now. If any problem occures, let me know.

Thanks for the help with debugging.

**Comment by TristanBossa** [comment]
Excellent it now works thanks!
