### ISSUE TITLE
Support for assignee data-field

### ISSUE THREAD

**Issue by yayyhb** [m-radzikowski/youtrack-issue-cards-printer#7]
### Background
I want to add the assignee data to a custom template, but it seems not to be sopported. Added `data-field="Assignee"`. [Object object] is displayed. Further we have no clue how to add the profileAvatar of a assignee.
### What to fix
Please wether provide a full list of fields, the exension is capable to handle OR if there is a bug, fix assignee data-field.

**Comment by m-radzikowski** [comment]
Hey,
I've just published version 0.3.1 with support for the "assignee" field. In custom template use `assigneeFullName` or `assigneeValue` (for just a login) to get the assignee.

On the other hand, support for profile avatar is very unlikely, as it would require doing HTTP requests for every user to firstly get user(s) ID, and then their avatars.
